plugins {
    id 'java'
    id 'application'
}

group = 'com.example'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.mysql:mysql-connector-j:+'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
        }
    }
}

application {
    mainClass = 'com.example.diary.ui.DiaryUI'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
